Repository Boegle/Boegle, pull requests merged in 2018-06, with the labels that each got.

#56 ADD - Get data with data from form
  controls/api.js
  controls/routes.js
  controls/socket.js
  src/js/modules/formResults.js
  views/components/form.ejs
  views/index.ejs
Labels: Must Have, enhancement

#61 FIX - Book animation made smoother
  src/js/modules/book.js
  src/styles/style.css
  views/components/book.ejs
Labels: Must Have, enhancement

#62 UPDATE - Added book animations and merged form
  src/js/modules/book.js
  src/styles/style.css
  views/components/book.ejs
  views/index.ejs
Labels: Must Have, enhancement

#65 UPDATE - index.ejs update
  src/img/iconBookBack.svg
  src/img/iconBookFront.svg
  src/img/iconBookOpen.svg
  src/img/iconBookUnder.svg
  src/js/modules/book.js
  src/styles/style.css
  views/components/book.ejs
  views/components/head.ejs
  views/components/sideMenu.ejs
  views/index.ejs
Labels: Must Have, enhancement

#66 ADD - A button that shows the result
  src/js/modules/book.js
  src/js/modules/formResults.js
  src/js/modules/resultCount.js
  src/js/modules/socket.js
  views/components/book.ejs
Labels: Should Have, enhancement

#90 UPDATE - Book almost finished!
  src/js/modules/book.js
  src/styles/style.css
Labels: Must Have, enhancement

#92 FIX - added id's to li's
  views/components/sideMenu.ejs
Labels: enhancement

#93 FIX - Change "this" to "that"
  src/js/modules/book.js
Labels: Must Have, enhancement

#108 ADD - Custom Select
  src/js/modules/book.js
  src/js/modules/formResults.js
  src/styles/style.css
  views/components/book.ejs
Labels: Should Have, enhancement
